PHOTOS_PASSWORD: Personal/photos.stho.net/Password
PHOTOS_ENDPOINT: Personal/photos.stho.net/Username
APPLE_DEV_CERT: Personal/apple-dev/dev-cert
APPLE_DEV_CERT_PASSWORD: Personal/apple-dev/dev-cert-password
ASC_ISSUER_ID: snap-sync/appstore-connect/issuer-id
ASC_KEY_ID: snap-sync/appstore-connect/key-id
ASC_AUTH_KEY: snap-sync/appstore-connect/auth-key
